[package]
name = "ex15_provenance"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
colored = "3.1.1"
dotenvy = "0.15.7"
futures-util = "0.3.34"
rand = "0.10.2"
reqwest = { version = "0.13.5", features = ["stream", "json"] }
reqwest-sse = "0.2.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
